name: build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  POWERSHELL_TELEMETRY_OPTOUT: 1
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_NOLOGO: true

defaults:
    run:
      shell: pwsh

jobs:
  build:
    name: Build and Test
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
    steps:
    - name: Check Version
      run: $PSVersionTable
    - uses: actions/checkout@v1
    - name: Test and Build
      run: ./build.ps1 -Force
    - uses: actions/upload-artifact@v1
      if: matrix.os == 'windows-latest'
      with:
        name: ClassExplorer
        path: ./Release/ClassExplorer
    - uses: actions/upload-artifact@v1
      if: matrix.os != 'windows-latest'
      with:
        name: ClassExplorer-${{ matrix.os }}
        path: ./Release/ClassExplorer
    - name: Upload Test Results
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: Unit Test Results (${{ matrix.os }})
        path: ./TestResults/Pester.xml
