name: publish
on:
  release:
      types: [ published ]

env:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  POWERSHELL_TELEMETRY_OPTOUT: 1
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_NOLOGO: true


defaults:
    run:
      shell: pwsh

jobs:
  build:
    name: Publish
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - name: Enable null conditional operators
      run: Enable-ExperimentalFeature PSNullConditionalOperators -ErrorAction Ignore -WarningAction Ignore
    - name: Test and Build
      run: ./build.ps1 -Force -Publish
      env:
        GALLERY_API_KEY: ${{ secrets.GALLERY_API_KEY }}
    - name: Upload Test Results
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: Unit Test Results
        path: ./TestResults/Pester.xml
